homepage:
    pattern:  /
    defaults: { _controller: {{ appname }}:{{ controller }}:welcome }

{{ appname }}:
    pattern:  /{{ controller }}
    defaults: { _controller: {{ appname }}:{{ controller }}:index }
