framework:
    charset:       UTF-8
    error_handler: null
    csrf_protection:
        enabled: true
        secret:  {{ csrf }}
    router:        { resource: "%kernel.root_dir%/config/routing.yml" }
    validation:    { enabled: true, annotations: true }
    templating:    { engines: ['{{ template_engine }}'] } #assets_version: SomeVersionScheme
    session:
        default_locale: en
        lifetime:       3600
        auto_start:     {{ session_start }}
        name:           {{ session_name }}
{{ twig }}
{{ assetic }}
{{ doctrine }}
{{ propel }}
{{ swiftmailer }}
{{ custom }}